# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK Keyboard Firmware"
product_name = "RMK Keyboard Pia"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "rp2040"

[matrix]
# Input and output pins are mandatory
output_pins = ["PIN_28", "PIN_27", "PIN_26", "PIN_22", "PIN_21", "PIN_20"]
input_pins = ["PIN_19", "PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 6
cols = 8
layers = 1
keymap = [
    [
        [No, KEY_GRAVE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6],
        [No, KEY_LWIN, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_V],
        [No, KEY_F8, KEY_CAPS_LOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_N],
        [No, KEY_F9, No, KEY_Y, KEY_X, KEY_C, KEY_SPACE, KEY_B],
        [KEY_LCTRL, KEY_LSHIFT, No, KEY_SPACE, No, No, No, No],
        [KEY_ESC, KEY_LALT, No, No, No, No, No, No]
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true
sk6803 = { pin = "PIN_11", led_count = 30 }



[storage]
# Storage feature is enabled by default
# enabled = false
